### PR TITLE
worked around inheritance problem

### PR DESCRIPTION
**Pull request by albertjan**
the inheritance problem persists, because when we inherit from an object
we copy over the prototype of the base object, and because the prototype
of object contained `__init__` we found that before we found `__init__`
in the dict of the base object. mro looks in the prototype of an object
when doing a typelookup.

To mitigate it I moved the `__init__` of object to the `$d` dict. It
solves the problem, but it doesn't solve the larger problem. We will
have to revisit this, to maybe not have the mro look in the prototype or
maybe to not copy python functions from the parent object.

Also the `test_set.py` tests still fail for different reasons now. 😕

### CODE REVIEW

**Comment by rixner** [comment]
@albertjan So, you believe this is an okay band aid to the problem?  I'm not offended by it...

The other failures turned out to be far more involved than I initially thought, but I do think we have fixes now.

Do you want this fix and our other fixes to just go in this pull request, or should they be in their own pull requests?

**Comment by albertjan** [comment]
I'm unsure about this band aid we put python function on the prototype of objects in many other places, they are all potentially affected by this problem. But the proper fix for this requires touching MRO and I'm very unsure about that too :smile:. This turned out to be a pretty fundamental problem.

Apply-ing the band-aid we maintain the status-quo which has served us well for a pretty long time. :smile:

**Comment by albertjan** [comment]
So after doing some manual labour and thinking about it some more, I figured out what the problem was. We were inadvertently doing a prototype walk where we were only interested in stuff declared on the prototype. 

So when we were looking for `__init__` on the prototype of the derived class it walked all the way up to object to find it. I've changed the check to only look for `ownProperties`. And now it does what it should.

**Comment by rixner** [comment]
I'm going to back this out.  I had trouble testing it, because my local repo was messed up, so I just merged it.  But, now that I've repaired my local repo, I get all kinds of failures for this:

```
test/unit/test_inheritance.py

Fail: Expected <type 'NoneType'> to have method '__repr__'
Fail: Expected <type 'NoneType'> to have method '__str__'
Fail: Expected <type 'NoneType'> to have method '__hash__'
Fail: Expected <type 'NoneType'> to have method '__eq__'
Fail: Expected <type 'NoneType'> to have method '__ne__'
Fail: Expected <type 'NoneType'> to have method '__lt__'
Fail: Expected <type 'NoneType'> to have method '__le__'
Fail: Expected <type 'NoneType'> to have method '__gt__'
Fail: Expected <type 'NoneType'> to have method '__ge__'
Fail: Expected <type 'NoneType'> to have method '__getattribute__'
Fail: Expected <type 'NoneType'> to have method '__setattr__'
Fail: Expected <type 'NotImplementedType'> to have method '__repr__'
Fail: Expected <type 'NotImplementedType'> to have method '__str__'
Fail: Expected <type 'NotImplementedType'> to have method '__hash__'
Fail: Expected <type 'NotImplementedType'> to have method '__eq__'
Fail: Expected <type 'NotImplementedType'> to have method '__ne__'
Fail: Expected <type 'NotImplementedType'> to have method '__lt__'
Fail: Expected <type 'NotImplementedType'> to have method '__le__'
Fail: Expected <type 'NotImplementedType'> to have method '__gt__'
Fail: Expected <type 'NotImplementedType'> to have method '__ge__'
Fail: Expected <type 'NotImplementedType'> to have method '__getattribute__'
Fail: Expected <type 'NotImplementedType'> to have method '__setattr__'
Tests failed in  BuiltinInheritance.test_none_notimplemented  
Fail: Expected <type 'int'> to have method '__repr__'
Fail: Expected <type 'int'> to have method '__str__'
Fail: Expected <type 'int'> to have method '__hash__'
Fail: Expected <type 'int'> to have method '__eq__'
<...snip...>
```

**Comment by albertjan** [comment]
Oh hmm that’s odd I’m sure I had it working like this. Back to the drawing board.


________________________________

**Comment by rixner** [comment]
@albertjan the problem could be on my end.  It ended up just being that one line change, right?

**Comment by rixner** [comment]
Yeah, when I make that one line change, there are all kinds of failures looking up the dunder methods in the Python 2 unit tests.  There are other lookup failures too on subclasses.  You must have had some other change somewhere, too?

**Pull request merged**
